name: auth_helper
description: A new Flutter package project.
version: 1.0.2
homepage: none
publish_to: none
environment:
  sdk: '>=2.17.5 <3.0.0'
  flutter: '>=1.17.0'
dependencies:
  cloud_firestore: ^3.3.0
  easy_localization: ^3.0.1
  firebase_auth: ^3.4.2
  flutter:
    sdk: flutter
  http: ^0.13.4
  tuple: ^2.0.0
  crypto: ^3.0.2
  pin_code_fields: ^7.4.0
  ui_kosmos_v4:
    git:
      publish_to: none
      url: YOUR_URL
      ref: main
  google_sign_in: ^5.4.0
  sign_in_with_apple: ^4.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter: null
